# Jekyll workshop-template evanwill
# https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

# Notes: 
# - pages with "nav: true" in front matter will be in header nav
# - figure include for centered images, put file in images directory and use: {% include figure.html img="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}

# Site settings
# title appears in the header
# Workshop Site Settings
title: "Evaluating Evaluations: Broader Impacts of Generative AI"
description: "A NeurIPS 2024 workshop on best practices for measuring the broader impacts of generative AI systems"
year: 2024

# Site settings
baseurl: "/"
url: "https://evaleval.github.io"

# Author settings
author: "Workshop Organizing Committee"

# Build settings
markdown: kramdown
relative_links:
  enabled: true
  collections: true

# Navigation settings
nav_pages:
  - index.md
  - overview.md
  - call-for-papers.md
  - schedule.md
  - people.md

# Colors
color_scheme: blue

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
