# Workshop Site Settings
# title appears in the header
title: "AAAI FIDU lab"
# description and keywords for meta tags
description: "Financial Inclusion through AI-Powered Document Understanding"
keywords: "LLM, finance, document understanding, financial inclusion, RAG"
year: 2025


# Site settings
baseurl: "/"
url: "https://aaai-fidu-lab.github.io"
emoji_favicon: "💡"

# Author settings
# author: "Workshop Organizing Committee"

# Build settings
markdown: kramdown
relative_links:
  enabled: true
  collections: true

# Navigation settings
nav_pages:
  - index.md    
  - organizers.md

# Colors
color_scheme: blue

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
