# Workshop Site Settings
title: "EvalEval 2024"
description: "A NeurIPS 2024 workshop on best practices for measuring the broader impacts of generative AI systems"
year: 2024

# Site settings
baseurl: "/"
url: "https://evaleval.github.io"
emoji_favicon: "💡"

# Author settings
# author: "Workshop Organizing Committee"

# Submission settings
submission_url: "https://openreview.net/group?id=NeurIPS.cc/2024/Workshop/EvalEval"

# Build settings
markdown: kramdown
relative_links:
  enabled: true
  collections: true

# Navigation settings
nav_pages:
  - index.md
  - overview.md
  - call-for-papers.md
  - schedule.md
  - people.md

# Colors
color_scheme: blue

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
